version: '3.8'
services:
  db:
    image: postgres
    container_name: hidden_tunes_db
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - ./configs/.env
    volumes:
      - ./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: govnonasrali
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - hidden_tunes_network 

  app:
    build: .
    container_name: hidden_tunes_app
    depends_on:
      - db
    restart: always
    ports:
      - "9999:9999"
    env_file:
      - ./configs/.env
    networks:
      - hidden_tunes_network     

volumes:
  db_data:


networks:
  hidden_tunes_network:
    name: hidden_tunes_network
    driver: bridge 

