version: '3.8'
services:
  db:
    image: postgres
    container_name: hidden_tunes_postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  app:
    build: .
    container_name: hidden_tunes_app
    depends_on:
      - db
    ports:
      - "9999:9999"
    env_file:
      - configs/.env
    restart: always
