CREATE TABLE AUDIO (
    ID SERIAL NOT NULL UNIQUE,
    JAMENDO_ID VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    ARTIST_NAME VARCHAR(255) NOT NULL,
    ALBUM_NAME VARCHAR(255) NOT NULL,
    ALBUM_IMAGE VARCHAR(255) NOT NULL,
    AUDIO VARCHAR(255) NOT NULL,
    AUDIODOWNLOAD VARCHAR(255) NOT NULL,
    RATE_LISTENED_TOTAL INTEGER NOT NULL
); 